### ISSUE TITLE
IllegalStateException while NetBeans startup

### ISSUE THREAD

**Issue by Chris2011** [mcheung63/MavenRunner#21]
If the IDE is open and got some configuration stuff done, I got this exception when the flag -J-ea is set inside the conf of NetBeans:

```
java.lang.IllegalStateException: Problem in some module which uses Window System: Window System API is required to be called from AWT thread only, see http://core.netbeans.org/proposals/threading/
	at org.netbeans.core.windows.WindowManagerImpl.warnIfNotInEDT(WindowManagerImpl.java:1764)
	at org.netbeans.core.windows.WindowManagerImpl.topComponentDisplayNameChanged(WindowManagerImpl.java:1353)
	at org.openide.windows.TopComponent.setName(TopComponent.java:978)
	at com.peter.mavenrunner.MavenRunnerTopComponent.<init>(MavenRunnerTopComponent.java:116)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openide.loaders.InstanceSupport.instanceCreate(InstanceSupport.java:222)
	at org.openide.loaders.InstanceDataObject$Ser.instanceCreate(InstanceDataObject.java:1442)
	at org.openide.loaders.InstanceDataObject.instanceCreate(InstanceDataObject.java:846)
	at org.openide.loaders.FolderLookup$ICItem.getInstance(FolderLookup.java:597)
	at org.openide.util.lookup.AbstractLookup$R.allInstances(AbstractLookup.java:1055)
	at org.openide.util.lookup.AbstractLookup$R.allInstances(AbstractLookup.java:1035)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.computeSingleResult(ProxyLookup.java:1285)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.computeDelegate(ProxyLookup.java:1123)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.delegate(ProxyLookup.java:1090)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.delegate(ProxyLookup.java:1073)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.isEmpty(ProxyLookup.java:1163)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.computeDelegate(ProxyLookup.java:1134)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.access$900(ProxyLookup.java:1051)
	at org.openide.util.lookup.ProxyLookup$LazyCollection$1.hasNext(ProxyLookup.java:1251)
	at org.netbeans.spi.project.support.DelegatingLookupImpl.doDelegate(DelegatingLookupImpl.java:134)
	at org.netbeans.spi.project.support.DelegatingLookupImpl.<init>(DelegatingLookupImpl.java:91)
	at org.netbeans.spi.project.support.LookupProviderSupport.createCompositeLookup(LookupProviderSupport.java:95)
	at org.netbeans.modules.web.clientproject.ClientSideProject.createLookup(ClientSideProject.java:585)
	at org.netbeans.modules.web.clientproject.ClientSideProject.<init>(ClientSideProject.java:231)
	at org.netbeans.modules.web.clientproject.ant.AntServices.factory(AntServices.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.netbeans.modules.project.ant.AntBasedGenericType.createProject(AntBasedGenericType.java:128)
	at org.netbeans.modules.project.ant.AntBasedProjectFactorySingleton.loadProject(AntBasedProjectFactorySingleton.java:264)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.createProject(NbProjectManager.java:401)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.access$300(NbProjectManager.java:94)
	at org.netbeans.modules.projectapi.nb.NbProjectManager$2.run(NbProjectManager.java:314)
	at org.netbeans.modules.projectapi.nb.NbProjectManager$2.run(NbProjectManager.java:243)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:209)
	at org.openide.util.Mutex.readAccess(Mutex.java:250)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.findProject(NbProjectManager.java:243)
	at org.netbeans.api.project.ProjectManager.findProject(ProjectManager.java:167)
	at org.netbeans.modules.projectapi.SimpleFileOwnerQueryImplementation.getOwner(SimpleFileOwnerQueryImplementation.java:161)
	at org.netbeans.modules.projectapi.SimpleFileOwnerQueryImplementation.getOwner(SimpleFileOwnerQueryImplementation.java:113)
	at org.netbeans.api.project.FileOwnerQuery.getOwner(FileOwnerQuery.java:150)
	at org.netbeans.modules.projectapi.ProjectSharabilityQuery2.getSharability(ProjectSharabilityQuery2.java:63)
	at org.netbeans.api.queries.SharabilityQuery.getSharability(SharabilityQuery.java:177)
	at org.netbeans.modules.git.utils.GitUtils.isIgnored(GitUtils.java:250)
	at org.netbeans.modules.git.FileStatusCache$IgnoredFilesHandler.run(FileStatusCache.java:874)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
```

And this:

```
java.lang.IllegalStateException: Problem in some module which uses Window System: Window System API is required to be called from AWT thread only, see http://core.netbeans.org/proposals/threading/
	at org.netbeans.core.windows.WindowManagerImpl.warnIfNotInEDT(WindowManagerImpl.java:1764)
	at org.netbeans.core.windows.WindowManagerImpl.topComponentToolTipChanged(WindowManagerImpl.java:1369)
	at org.openide.windows.TopComponent.setToolTipText(TopComponent.java:1068)
	at com.peter.mavenrunner.MavenRunnerTopComponent.<init>(MavenRunnerTopComponent.java:117)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openide.loaders.InstanceSupport.instanceCreate(InstanceSupport.java:222)
	at org.openide.loaders.InstanceDataObject$Ser.instanceCreate(InstanceDataObject.java:1442)
	at org.openide.loaders.InstanceDataObject.instanceCreate(InstanceDataObject.java:846)
	at org.openide.loaders.FolderLookup$ICItem.getInstance(FolderLookup.java:597)
	at org.openide.util.lookup.AbstractLookup$R.allInstances(AbstractLookup.java:1055)
	at org.openide.util.lookup.AbstractLookup$R.allInstances(AbstractLookup.java:1035)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.computeSingleResult(ProxyLookup.java:1285)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.computeDelegate(ProxyLookup.java:1123)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.delegate(ProxyLookup.java:1090)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.delegate(ProxyLookup.java:1073)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.toArray(ProxyLookup.java:1179)
	at java.util.ArrayList.addAll(ArrayList.java:577)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.computeDelegate(ProxyLookup.java:1143)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.delegate(ProxyLookup.java:1090)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.delegate(ProxyLookup.java:1073)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.isEmpty(ProxyLookup.java:1163)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.computeDelegate(ProxyLookup.java:1134)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.access$900(ProxyLookup.java:1051)
	at org.openide.util.lookup.ProxyLookup$LazyCollection$1.hasNext(ProxyLookup.java:1251)
	at org.netbeans.spi.project.support.DelegatingLookupImpl.doDelegate(DelegatingLookupImpl.java:134)
	at org.netbeans.spi.project.support.DelegatingLookupImpl.<init>(DelegatingLookupImpl.java:91)
	at org.netbeans.spi.project.support.LookupProviderSupport.createCompositeLookup(LookupProviderSupport.java:111)
	at org.netbeans.modules.maven.NbMavenProjectImpl.<init>(NbMavenProjectImpl.java:266)
	at org.netbeans.modules.maven.NbMavenProjectFactory.loadProject(NbMavenProjectFactory.java:118)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.createProject(NbProjectManager.java:401)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.access$300(NbProjectManager.java:94)
	at org.netbeans.modules.projectapi.nb.NbProjectManager$2.run(NbProjectManager.java:314)
	at org.netbeans.modules.projectapi.nb.NbProjectManager$2.run(NbProjectManager.java:243)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:209)
	at org.openide.util.Mutex.readAccess(Mutex.java:250)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.findProject(NbProjectManager.java:243)
	at org.netbeans.api.project.ProjectManager.findProject(ProjectManager.java:167)
	at org.netbeans.modules.project.ui.OpenProjectList.URLs2Projects(OpenProjectList.java:1260)
	at org.netbeans.modules.project.ui.OpenProjectList.access$1400(OpenProjectList.java:137)
	at org.netbeans.modules.project.ui.OpenProjectList$LoadOpenProjects.loadOnBackground(OpenProjectList.java:474)
	at org.netbeans.modules.project.ui.OpenProjectList$LoadOpenProjects.run(OpenProjectList.java:394)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
```

You can test it inside the nightlies or in stable, when you add -J-ea to the conf.

**Comment by mcheung63** [comment]
Yes and thanks, the issue exists. Many people is having this problem http://statistics.netbeans.org/exceptions/detail.do?id=90178 , i am trying to fix it.

<img width="1680" alt="screen shot 2017-08-25 at 2 39 30 pm" src="https://user-images.githubusercontent.com/1779905/29702604-8f2a7dca-89a4-11e7-9215-5a860ae9c664.png">

**Comment by mcheung63** [comment]
Fixed changing
		setName(Bundle.CTL_MavenRunnerTopComponent());
		etToolTipText(Bundle.HINT_MavenRunnerTopComponent());

to

		SwingUtilities.invokeLater(new Runnable() {
			public void run() {
				setName(Bundle.CTL_MavenRunnerTopComponent());
				setToolTipText(Bundle.HINT_MavenRunnerTopComponent());
			}
		});

**Comment by Chris2011** [comment]
great, thx.
